enum Measurement {
  PINCH
  TEASPOON
  TABLESPOON
  OUNCE
  FLUID_OUNCE
  POUND
  CUP
  PINT
  QUART
  GALLON
  MILLILITER
  LITER
  PACKAGE
  GRAM
  KILOGRAM
  EACH
  JAR
  BOX
}

type Comment {
  author: String!
  text: String!
  recipe: Recipe!
}

type Ingredient {
  amount: Float!
  measurement: Measurement!
  item: String!
  recipe: Recipe!
}

type Recipe {
  author: String!
  title: String!
  description: String
  ingredients: [Ingredient!]! @relation
  steps: [String!]!
  imageUrl: String!
  source: String
  servings: String!
  totalTime: String!
  tags: [String]
  notes: String
  comments: [Comment]! @relation
}

type Query {
  recipesByTimestampDesc: [Recipe!]! @resolver(name: "all_recipes_by_timestamp", paginated: true)
  recipes: [Recipe!]!
  ingredients: [Ingredient!]!
  comments: [Comment!]!
  # recipesByIngredients(ingredients: [String!]!): [Recipe]!
}
